### PR TITLE
CI: added ci

### PR DESCRIPTION
**Pull request by mgerhardy**

### CODE REVIEW

**Review by xesf — APPROVED** [review]
Awesome, thanks for doing it!!

**Comment by xesf** [comment]
@mgerhardy 
Looks like it does not like the %INCLUDE% and its failing to build.

**Comment by mgerhardy** [comment]
@xesf you were too fast for me clicking draft ;)
i was just trying to get this running - making this a draft to get some feedback. I get a few errors that my limited watcom experience can't parse.

https://github.com/mgerhardy/lba1-classic-community/tree/pr/ci here you can see the latest commit

**Comment by mgerhardy** [comment]
https://github.com/mgerhardy/lba1-classic-community/runs/6645091520?check_suite_focus=true and here the errors of the build

**Pull request merged**
